spring:
  application:
    name: organizadorTerritoriosJW
  datasource:
    url: jdbc:postgresql://localhost:5432/territorios
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    open-in-view: true
    show-sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
server:
  port: 8081